# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
# db/seeds.rb

puts "Cleaning up existing demo data..."
demo_user = User.find_by(email: "demo@rentflow.com")
if demo_user
  RentPayment.where(landlord: demo_user).destroy_all
    Tenant.where(landlord: demo_user).destroy_all
      Unit.joins(:property).where(properties: { user: demo_user }).destroy_all
        Property.where(user: demo_user).destroy_all
          demo_user.destroy
          end

          puts "Creating demo user..."
          user = User.create!(
            email:                 "demo@rentflow.com",
              password:              "Demo1234!",
                password_confirmation: "Demo1234!",
                  first_name:            "Demo",
                    last_name:             "Landlord",
                      company_name:          "Rentflow Demo Properties"
                      )

                      puts "Creating properties..."
                      sunset = Property.create!(
                        user:        user,
                          name:        "Sunset Apartments",
                            address:     "123 Ngong Road",
                              city:        "Nairobi",
                                description: "Modern apartments in Kilimani with ample parking and 24hr security."
                                )

                                greenview = Property.create!(
                                  user:        user,
                                    name:        "Greenview Court",
                                      address:     "45 Thika Road",
                                        city:        "Nairobi",
                                          description: "Spacious units near Garden City Mall with rooftop access."
                                          )

                                          lakeside = Property.create!(
                                            user:        user,
                                              name:        "Lakeside Residences",
                                                address:     "8 Nyali Road",
                                                  city:        "Mombasa",
                                                    description: "Beachside apartments with ocean views and a shared pool."
                                                    )

                                                    puts "Creating units..."

                                                    # Sunset Apartments — 8 units (6 occupied, 2 vacant)
                                                    sunset_units = [
                                                      { unit_number: "A1", floor: 1, rent_amount: 25000, status: "occupied" },
                                                        { unit_number: "A2", floor: 1, rent_amount: 25000, status: "occupied" },
                                                          { unit_number: "A3", floor: 1, rent_amount: 25000, status: "vacant"   },
                                                            { unit_number: "B1", floor: 2, rent_amount: 28000, status: "occupied" },
                                                              { unit_number: "B2", floor: 2, rent_amount: 28000, status: "occupied" },
                                                                { unit_number: "B3", floor: 2, rent_amount: 28000, status: "vacant"   },
                                                                  { unit_number: "C1", floor: 3, rent_amount: 32000, status: "occupied" },
                                                                    { unit_number: "C2", floor: 3, rent_amount: 32000, status: "occupied" },
                                                                    ].map { |u| Unit.create!(property: sunset, **u) }

                                                                    # Greenview Court — 6 units (5 occupied, 1 vacant)
                                                                    greenview_units = [
                                                                      { unit_number: "G1", floor: 1, rent_amount: 18000, status: "occupied" },
                                                                        { unit_number: "G2", floor: 1, rent_amount: 18000, status: "occupied" },
                                                                          { unit_number: "G3", floor: 2, rent_amount: 20000, status: "occupied" },
                                                                            { unit_number: "G4", floor: 2, rent_amount: 20000, status: "vacant"   },
                                                                              { unit_number: "G5", floor: 3, rent_amount: 22000, status: "occupied" },
                                                                                { unit_number: "G6", floor: 3, rent_amount: 22000, status: "occupied" },
                                                                                ].map { |u| Unit.create!(property: greenview, **u) }

                                                                                # Lakeside Residences — 4 units (3 occupied, 1 vacant)
                                                                                lakeside_units = [
                                                                                  { unit_number: "L1", floor: 1, rent_amount: 35000, status: "occupied" },
                                                                                    { unit_number: "L2", floor: 1, rent_amount: 35000, status: "occupied" },
                                                                                      { unit_number: "L3", floor: 2, rent_amount: 40000, status: "occupied" },
                                                                                        { unit_number: "L4", floor: 2, rent_amount: 40000, status: "vacant"   },
                                                                                        ].map { |u| Unit.create!(property: lakeside, **u) }

                                                                                        puts "Creating tenants..."

                                                                                        tenants_data = [
                                                                                          # Sunset Apartments
                                                                                            {
                                                                                                first_name: "James",    last_name: "Mwangi",
                                                                                                    email: "james.mwangi@email.com",   phone: "+254711001001",
                                                                                                        national_id: "23456781", lease_start_date: "2024-01-01",
                                                                                                            lease_end_date: "2024-12-31", unit: sunset_units[0]
                                                                                                              },
                                                                                                                {
                                                                                                                    first_name: "Amina",    last_name: "Hassan",
                                                                                                                        email: "amina.hassan@email.com",   phone: "+254711001002",
                                                                                                                            national_id: "23456782", lease_start_date: "2024-03-01",
                                                                                                                                lease_end_date: "2025-02-28", unit: sunset_units[1]
                                                                                                                                  },
                                                                                                                                    {
                                                                                                                                        first_name: "Brian",    last_name: "Otieno",
                                                                                                                                            email: "brian.otieno@email.com",   phone: "+254711001003",
                                                                                                                                                national_id: "23456783", lease_start_date: "2023-06-01",
                                                                                                                                                    lease_end_date: "2025-05-31", unit: sunset_units[3]
                                                                                                                                                      },
                                                                                                                                                        {
                                                                                                                                                            first_name: "Fatuma",   last_name: "Ali",
                                                                                                                                                                email: "fatuma.ali@email.com",     phone: "+254711001004",
                                                                                                                                                                    national_id: "23456784", lease_start_date: "2024-02-01",
                                                                                                                                                                        lease_end_date: "2025-01-31", unit: sunset_units[4]
                                                                                                                                                                          },
                                                                                                                                                                            {
                                                                                                                                                                                first_name: "Kevin",    last_name: "Kamau",
                                                                                                                                                                                    email: "kevin.kamau@email.com",    phone: "+254711001005",
                                                                                                                                                                                        national_id: "23456785", lease_start_date: "2024-04-01",
                                                                                                                                                                                            lease_end_date: "2025-03-31", unit: sunset_units[6]
                                                                                                                                                                                              },
                                                                                                                                                                                                {
                                                                                                                                                                                                    first_name: "Grace",    last_name: "Njeri",
                                                                                                                                                                                                        email: "grace.njeri@email.com",    phone: "+254711001006",
                                                                                                                                                                                                            national_id: "23456786", lease_start_date: "2023-09-01",
                                                                                                                                                                                                                lease_end_date: "2024-08-31", unit: sunset_units[7]
                                                                                                                                                                                                                  },
                                                                                                                                                                                                                    # Greenview Court
                                                                                                                                                                                                                      {
                                                                                                                                                                                                                          first_name: "Peter",    last_name: "Ochieng",
                                                                                                                                                                                                                              email: "peter.ochieng@email.com",  phone: "+254711001007",
                                                                                                                                                                                                                                  national_id: "23456787", lease_start_date: "2024-01-01",
                                                                                                                                                                                                                                      lease_end_date: "2024-12-31", unit: greenview_units[0]
                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                              first_name: "Mercy",    last_name: "Wanjiku",
                                                                                                                                                                                                                                                  email: "mercy.wanjiku@email.com",  phone: "+254711001008",
                                                                                                                                                                                                                                                      national_id: "23456788", lease_start_date: "2024-05-01",
                                                                                                                                                                                                                                                          lease_end_date: "2025-04-30", unit: greenview_units[1]
                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                  first_name: "David",    last_name: "Kipchoge",
                                                                                                                                                                                                                                                                      email: "david.kipchoge@email.com", phone: "+254711001009",
                                                                                                                                                                                                                                                                          national_id: "23456789", lease_start_date: "2023-11-01",
                                                                                                                                                                                                                                                                              lease_end_date: "2024-10-31", unit: greenview_units[2]
                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                      first_name: "Lilian",   last_name: "Auma",
                                                                                                                                                                                                                                                                                          email: "lilian.auma@email.com",    phone: "+254711001010",
                                                                                                                                                                                                                                                                                              national_id: "23456790", lease_start_date: "2024-06-01",
                                                                                                                                                                                                                                                                                                  lease_end_date: "2025-05-31", unit: greenview_units[4]
                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                          first_name: "Samuel",   last_name: "Mutua",
                                                                                                                                                                                                                                                                                                              email: "samuel.mutua@email.com",   phone: "+254711001011",
                                                                                                                                                                                                                                                                                                                  national_id: "23456791", lease_start_date: "2024-03-01",
                                                                                                                                                                                                                                                                                                                      lease_end_date: "2025-02-28", unit: greenview_units[5]
                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                          # Lakeside Residences
                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                first_name: "Zara",     last_name: "Mohamed",
                                                                                                                                                                                                                                                                                                                                    email: "zara.mohamed@email.com",   phone: "+254711001012",
                                                                                                                                                                                                                                                                                                                                        national_id: "23456792", lease_start_date: "2024-01-01",
                                                                                                                                                                                                                                                                                                                                            lease_end_date: "2024-12-31", unit: lakeside_units[0]
                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                    first_name: "Hassan",   last_name: "Salim",
                                                                                                                                                                                                                                                                                                                                                        email: "hassan.salim@email.com",   phone: "+254711001013",
                                                                                                                                                                                                                                                                                                                                                            national_id: "23456793", lease_start_date: "2023-07-01",
                                                                                                                                                                                                                                                                                                                                                                lease_end_date: "2024-06-30", unit: lakeside_units[1]
                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                        first_name: "Caroline", last_name: "Chebet",
                                                                                                                                                                                                                                                                                                                                                                            email: "caroline.chebet@email.com",phone: "+254711001014",
                                                                                                                                                                                                                                                                                                                                                                                national_id: "23456794", lease_start_date: "2024-02-01",
                                                                                                                                                                                                                                                                                                                                                                                    lease_end_date: "2025-01-31", unit: lakeside_units[2]
                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                      ]

                                                                                                                                                                                                                                                                                                                                                                                      tenants = tenants_data.map do |t|
                                                                                                                                                                                                                                                                                                                                                                                        unit = t.delete(:unit)
                                                                                                                                                                                                                                                                                                                                                                                          tenant = Tenant.create!(landlord: user, **t)
                                                                                                                                                                                                                                                                                                                                                                                            unit.update!(tenant: tenant, status: "occupied")
                                                                                                                                                                                                                                                                                                                                                                                              tenant
                                                                                                                                                                                                                                                                                                                                                                                              end

                                                                                                                                                                                                                                                                                                                                                                                              puts "Creating rent payments (6 months history)..."

                                                                                                                                                                                                                                                                                                                                                                                              def payment_status(month, year, index)
                                                                                                                                                                                                                                                                                                                                                                                                today = Date.current
                                                                                                                                                                                                                                                                                                                                                                                                  payment_date = Date.new(year, month, 1)
                                                                                                                                                                                                                                                                                                                                                                                                    return "pending" if payment_date >= Date.new(today.year, today.month, 1)
                                                                                                                                                                                                                                                                                                                                                                                                      # Simulate a few overdue, mostly paid
                                                                                                                                                                                                                                                                                                                                                                                                        index % 7 == 0 ? "overdue" : "paid"
                                                                                                                                                                                                                                                                                                                                                                                                        end

                                                                                                                                                                                                                                                                                                                                                                                                        6.downto(0).each do |months_ago|
                                                                                                                                                                                                                                                                                                                                                                                                          date  = months_ago.months.ago
                                                                                                                                                                                                                                                                                                                                                                                                            month = date.month
                                                                                                                                                                                                                                                                                                                                                                                                              year  = date.year.to_i

                                                                                                                                                                                                                                                                                                                                                                                                                tenants.each_with_index do |tenant, index|
                                                                                                                                                                                                                                                                                                                                                                                                                    unit   = tenant.unit
                                                                                                                                                                                                                                                                                                                                                                                                                        status = payment_status(month, year, index)

                                                                                                                                                                                                                                                                                                                                                                                                                            RentPayment.create!(
                                                                                                                                                                                                                                                                                                                                                                                                                                  tenant:      tenant,
                                                                                                                                                                                                                                                                                                                                                                                                                                        unit:        unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                              property:    unit.property,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    landlord:    user,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          month:       month,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                year:        year,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      amount_due:  unit.rent_amount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            amount_paid: status == "paid" ? unit.rent_amount : 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status:      status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        due_date:    Date.new(year, month, 5),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              paid_date:   status == "paid" ? Date.new(year, month, rand(1..4)) : nil,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    notes:       status == "paid" ? "Paid via Mpesa" : ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          end

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "========================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "  Seed complete!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "========================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "  Email:      demo@rentflow.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "  Password:   Demo1234!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "  Properties: 3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "  Units:      18 (14 occupied, 4 vacant)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "  Tenants:    14"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "  Payments:   #{RentPayment.where(landlord: user).count} records (7 months)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          puts "========================================="